name: Sync Notion Tasks

on:
  schedule:
    - cron: '*/48 * * * *'  # 毎日8時0分に実行（1時間ごとに実行）
  workflow_dispatch:  # 手動実行用
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: 依存関係をインストール
        run: pip install requests

      - name: スクリプトを実行
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python sync_notion.py
